[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc = "0.8.29"
cbor_metadata = true
evmVersion = "cancun"
build_info = true
extra_output = ["storageLayout"]
optimizer = true
optimizer_runs = 200

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.3.0"
